# Generated by Django 3.1.1 on 2020-09-25 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0004_film_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='user',
            new_name='author',
        ),
    ]
