# Generated by Django 3.1.1 on 2020-09-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0006_film_krotki_opis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='opis',
            field=models.TextField(default='', max_length=195),
        ),
    ]
