# Generated by Django 3.1.1 on 2020-09-27 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0009_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='com',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filmyweb.comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
