# Generated by Django 3.1.1 on 2020-09-27 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0011_auto_20200927_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='komentarz',
        ),
    ]
