# Generated by Django 3.1.1 on 2020-09-27 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0013_auto_20200927_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='com',
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='filmyweb.film'),
        ),
    ]
