# Generated by Django 3.1.1 on 2020-09-27 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filmyweb', '0015_comments_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='aut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
