# Generated by Django 3.1.1 on 2020-09-28 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filmyweb', '0018_auto_20200927_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='likes',
            field=models.ManyToManyField(related_name='poj_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
