# Generated by Django 3.1.1 on 2020-10-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0019_film_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='krotki_opis',
        ),
    ]
